### ISSUE TITLE
MailgunModule.forAsyncRoot

### ISSUE THREAD

**Issue by juliokriger** [NextNC/nestjs-mailgun#1]
Hi!

It would be nice to hace async registration.

Also in ConfigurationMailgun I think it's misspelled AKI_KEY, it should bi API_KEY.

Regards

**Comment by spinegar** [comment]
Async registration would be great! I may move away from this package without it.

**Comment by NextNC** [comment]
I will do it until the end of this week 👍

**Comment by NextNC** [comment]
Hi @spinegar,
I'm sorry... I thought that I would had time last week. I will try to do it this week 👍

**Comment by spinegar** [comment]
Thanks @NextNC ! Looking forward to the update!

**Comment by NextNC** [comment]
Hi @spinegar just published the new version 👍
