### ISSUE TITLE
Can't pass custom data to template

### ISSUE THREAD

**Issue by dewpboer** [NextNC/nestjs-mailgun#11]
Hello,

From your documentation I don't see an option to pass custom variables.
In my templates I use a var like {{name}}.
I tried using "recipient-variables" like this, but it doesn't work for me.
{
 name: 'My name'
}

If it is possible, an example will be appreciated!

With kind regards,
Andy

**Comment by NextNC** [comment]
Hi @dewpboer this week I was focused in another opened issue. But, I will take a look in yours in the next week 👍

**Comment by morok0x** [comment]
Hi, I'm following up on the issue, if it was resolved. Thank you.

**Comment by davevurby** [comment]
Hi! Any updates on this issue? Thank you!

**Comment by razinj** [comment]
Anything new on this issue ?

**Comment by razinj** [comment]
Hello everyone, Since I was having this issue too and there is no response form the maintainer of this repo.

I tried some things but the only way to make it work was the following :
- In your options object, remove the object's type and set it to `any`
- Add this entry to the options object.

```
  'h:X-Mailgun-Variables': JSON.stringify({
    name: 'nizar'
  })
```

`h:X-Mailgun-Variables` is from the official documentation of MailGun.

This hack worked for me while setting a template name that has `{{name}}` in the template as my variable.

I hope that the maintainer fixes this so we have an official solution, meanwhile here is it to get going.

**Comment by dewpboer** [comment]
We solved it in the following way, and this can easily be implemented by the maintainer:

First we created our own service: **mailgun-api.service.ts**
`import { Injectable } from '@nestjs/common';
import { MailgunService } from '@nextnm/nestjs-mailgun';
import { MailgunEmailModel } from '../model/mailgun-email.model';

@Injectable()
export class MailgunApiService {
  constructor(private mailgunService: MailgunService) {}

  public async send(mailgunEmail: MailgunEmailModel) {
    if (mailgunEmail.vars) {
      mailgunEmail['h:X-Mailgun-Variables'] = JSON.stringify(
        mailgunEmail.getVars(),
      );
    }

    return this.mailgunService.sendEmail(mailgunEmail);
  }
}
`

We also created a custom email model which extends the EmailOptions class: **mailgun-email.model.ts**
`import { EmailOptions } from '@nextnm/nestjs-mailgun';

export class MailgunEmailModel implements EmailOptions {
  public from = '';
  public to = '';
  public subject = '';
  public attachment?: string = '';
  public template?: string = '';
  public text?: string = '';
  public html?: string = '';
  public vars?: { [key: string]: any } = {};

  public setFrom(from: string): MailgunEmailModel {
    this.from = from;
    return this;
  }

  public getFrom(): string {
    return this.from;
  }

  public setTo(to: string): MailgunEmailModel {
    this.to = to;
    return this;
  }

  public getTo(): string {
    return this.to;
  }

  public setSubject(subject: string): MailgunEmailModel {
    this.subject = subject;
    return this;
  }

  public getSubject(): string {
    return this.subject;
  }

  public setAttachment(attachment: string): MailgunEmailModel {
    this.attachment = attachment;
    return this;
  }

  public getAttachment(): string {
    return this.attachment;
  }

  public setTemplate(template: string): MailgunEmailModel {
    this.template = template;
    return this;
  }

  public getTemplate(): string {
    return this.template;
  }

  public setText(text: string): MailgunEmailModel {
    this.text = text;
    return this;
  }

  public getText(): string {
    return this.text;
  }

  public setHtml(html: string): MailgunEmailModel {
    this.html = html;
    return this;
  }

  public getHtml(): string {
    return this.html;
  }

  public setVar(index: string, value: string): MailgunEmailModel {
    this.vars[index] = value;
    return this;
  }

  public getVars(): { [key: string]: any } {
    return this.vars;
  }
}
`
And then you can use it in your code like this:
`const mailgunEmail = new MailgunEmailModel();
    mailgunEmail.setFrom('Example <noreply@example.com>');
    mailgunEmail.setTo('example@example.com');
    mailgunEmail.setSubject('Subject');
    mailgunEmail.setTemplate('your_mailgun_template');
    mailgunEmail.setVar('name', 'John Doe');
    this.mailgunService.send(mailgunEmail);`

We didn't have any issues with this in the past 3 months. It's flexible and it works.

Hope this helps someone!

**Comment by razinj** [comment]
@dewpboer  Thank you, I hope the maintainer sees this and add it.

Glad you found a solution and posting it for others, I might as well be doing the same thing in the next sprint.

**Comment by NextNC** [comment]
Hi guys sorry for not being paying much attention to this repo. I already released a new version, where I believe it's fixed. Please let me know what you think about it. I won't close this issue until you give me green light. Thank you for your help and for sharing your solutions! 👍

**Comment by razinj** [comment]
Thank you, I will test very soon and let you know.
