### ISSUE TITLE
Send email returned value

### ISSUE THREAD

**Issue by faan11** [NextNC/nestjs-mailgun#13]
I'm using this library for a project.
I found out that the method sendEmail returns a boolean promise.
However, the method resolves a body object. 
Is it an error?

**Comment by NextNC** [comment]
Hi @faan11! Yes it was a typo... I will replace for any right now. But if you could help me finding the correct typing, it would be great 👍

**Comment by faan11** [comment]
Sorry, i was lazy and i forgot to respond. 
As you can see from here, if the message was sent then it returns an object composed of "message" and id fields. Both are strings.

https://www.mailgun.com/blog/tracking-replies-in-mailgun-or-any-other-email/
