### ISSUE TITLE
Found high vulnerability 

### ISSUE THREAD

**Issue by RoyBkker** [NextNC/nestjs-mailgun#17]
While installing, it gives this warning "netmask npm package vulnerable to octal input data"

More info here:
https://www.npmjs.com/advisories/1658

Good to bump netmask package to >=2.0.1

**Comment by kkarimi** [comment]
@NextNC can we please swap to the official mailgun package? see [here](https://github.com/mailgun/mailgun-js/issues/124) and [here](https://github.com/mailgun/mailgun-js-boland/issues/269)

**Comment by NextNC** [comment]
It's already done to the latest version 👍
